theme: jekyll-theme-slate
title: QB64.com
description: QB64 is a modern extended BASIC programming language that retains QBasic/QuickBASIC 4.5 compatibility and compiles native binaries for Windows, Linux, and macOS.
include: 
 - wiki/_ACCEPTFILEDROP.md
 - wiki/_ACOS.md
 - wiki/_ACOSH.md
 - wiki/_ALLOWFULLSCREEN.md
 - wiki/_ALPHA.md
 - wiki/_ALPHA32.md
 - wiki/_ASIN.md
 - wiki/_ASINH.md
 - wiki/_ASSERT.md
 - wiki/_ATAN2.md
 - wiki/_ATANH.md
 - wiki/_AUTODISPLAY-(function).md
 - wiki/_AUTODISPLAY.md
 - wiki/_AXIS.md
 - wiki/_BACKGROUNDCOLOR.md
 - wiki/_BIT.md
 - wiki/_BLEND-(function).md
 - wiki/_BLEND.md
 - wiki/_BLINK-(function).md
 - wiki/_BLINK.md
 - wiki/_BLUE.md
 - wiki/_BLUE32.md
 - wiki/_BUTTON.md
 - wiki/_BUTTONCHANGE.md
 - wiki/_BYTE.md
 - wiki/_CAPSLOCK-(function).md
 - wiki/_CAPSLOCK.md
 - wiki/_CEIL.md
 - wiki/_CINP.md
 - wiki/_CLEARCOLOR-(function).md
 - wiki/_CLEARCOLOR.md
 - wiki/_CLIP.md
 - wiki/_CLIPBOARD$-(statement).md
 - wiki/_CLIPBOARD$.md
 - wiki/_CLIPBOARDIMAGE-(function).
 - wiki/_CLIPBOARDIMAGE.md
 - wiki/_COMMANDCOUNT.md
 - wiki/_CONNECTED.md
 - wiki/_CONNECTIONADDRESS$.md
 - wiki/_CONNECTIONADDRESS.md
 - wiki/_CONSOLE.md
 - wiki/_CONSOLEINPUT.md
 - wiki/_CONSOLETITLE.md
 - wiki/_CONTINUE.md
 - wiki/_CONTROLCHR-(function).md
 - wiki/_CONTROLCHR.md
 - wiki/_COPYIMAGE.md
 - wiki/_COPYPALETTE.md
 - wiki/_CV.md
 - wiki/_CWD$.md
 - wiki/_D2G.md
 - wiki/_D2R.md
 - wiki/_DEFAULTCOLOR.md
 - wiki/_DEFINE.md
 - wiki/_DEFLATE$.md
 - wiki/_DELAY.md
 - wiki/_DEPTHBUFFER.md
 - wiki/_DESKTOPHEIGHT.md
 - wiki/_DESKTOPWIDTH.md
 - wiki/_DEST-(function).md
 - wiki/_DEST.md
 - wiki/_DEVICE$.md
 - wiki/_DEVICEINPUT.md
 - wiki/_DEVICES.md
 - wiki/_DIR$.md
 - wiki/_DIREXISTS.md
 - wiki/_DISPLAY-(function).md
 - wiki/_DISPLAY.md
 - wiki/_DISPLAYORDER.md
 - wiki/_DONTBLEND.md
 - wiki/_DONTWAIT.md
 - wiki/_DROPPEDFILE.md
 - wiki/_ECHO.md
 - wiki/_ENVIRONCOUNT.md
 - wiki/_ERRORLINE.md
 - wiki/_ERRORMESSAGE$.md
 - wiki/_EXIT-(function).md
 - wiki/_FILEEXISTS.md
 - wiki/_FINISHDROP.md
 - wiki/_FLOAT.md
 - wiki/_FONT-(function).md
 - wiki/_FONT.md
 - wiki/_FONTHEIGHT-(function).md
 - wiki/_FONTHEIGHT.md
 - wiki/_FONTWIDTH-(function).md
 - wiki/_FONTWIDTH.md
 - wiki/_FREEFONT.md
 - wiki/_FREEIMAGE.md
 - wiki/_FREETIMER.md
 - wiki/_FULLSCREEN-(function).md
 - wiki/_FULLSCREEN.md
 - wiki/_G2D.md
 - wiki/_G2R.md
 - wiki/_gl.md
 - wiki/_glcissor.md
 - wiki/_gleadBuffer.md
 - wiki/_gleadPixels.md
 - wiki/_gleedbackBuffer.md
 - wiki/_gleleteTextures.md
 - wiki/_glenTextures.md
 - wiki/_glepthFunc.md
 - wiki/_glepthMask.md
 - wiki/_glepthRange.md
 - wiki/_glet.md
 - wiki/_gletError.md
 - wiki/_gletString.md
 - wiki/_gletTexImage.md
 - wiki/_glexImage1D.md
 - wiki/_glexImage2D.md
 - wiki/_glexSubImage1D.md
 - wiki/_glexSubImage2D.md
 - wiki/_gliewport.md
 - wiki/_glindTexture.md
 - wiki/_glineWidth.md
 - wiki/_glinish.md
 - wiki/_glint.md
 - wiki/_gllear.md
 - wiki/_gllearColor.md
 - wiki/_gllearDepth.md
 - wiki/_gllearStencil.md
 - wiki/_gllush.md
 - wiki/_glnable.md
 - wiki/_glogicOp.md
 - wiki/_glointSize.md
 - wiki/_glolorMask.md
 - wiki/_glolygonMode.md
 - wiki/_glolygonOffset.md
 - wiki/_glopyTexImage1D.md
 - wiki/_glopyTexImage2D.md
 - wiki/_glopyTexSubImage1D.md
 - wiki/_glopyTexSubImage2D.md
 - wiki/_glrawArrays.md
 - wiki/_glrawBuffer.md
 - wiki/_glrawElements.md
 - wiki/_GLRENDER.md
 - wiki/_glrontFace.md
 - wiki/_glsEnabled.md
 - wiki/_glsTexture.md
 - wiki/_gltencilFunc.md
 - wiki/_gltencilMask.md
 - wiki/_gltencilOp.md
 - wiki/_glullFace.md
 - wiki/_GREEN.md
 - wiki/_GREEN32.md
 - wiki/_HEIGHT.md
 - wiki/_HIDE.md
 - wiki/_HYPOT.md
 - wiki/_ICON.md
 - wiki/_INCLERRORFILE$.md
 - wiki/_INCLERRORLINE.md
 - wiki/_INFLATE$.md
 - wiki/_INSTRREV.md
 - wiki/_INTEGER64.md
 - wiki/_KEYCLEAR.md
 - wiki/_KEYDOWN.md
 - wiki/_KEYHIT.md
 - wiki/_LASTAXIS.md
 - wiki/_LASTBUTTON.md
 - wiki/_LASTWHEEL.md
 - wiki/_LIMIT.md
 - wiki/_LOADFONT.md
 - wiki/_LOADIMAGE.md
 - wiki/_MAPTRIANGLE.md
 - wiki/_MAPUNICODE-(function).md
 - wiki/_MAPUNICODE.md
 - wiki/_MEM-(function).md
 - wiki/_MEM.md
 - wiki/_MEMCOPY.md
 - wiki/_MEMELEMENT.md
 - wiki/_MEMEXISTS.md
 - wiki/_MEMFILL.md
 - wiki/_MEMFREE.md
 - wiki/_MEMGET-(function).md
 - wiki/_MEMGET.md
 - wiki/_MEMIMAGE.md
 - wiki/_MEMNEW.md
 - wiki/_MEMPUT.md
 - wiki/_MEMSOUND.md
 - wiki/_MK$.md
 - wiki/_MOUSEBUTTON.md
 - wiki/_MOUSEHIDE.md
 - wiki/_MOUSEINPUT.md
 - wiki/_MOUSEMOVE.md
 - wiki/_MOUSEMOVEMENTX.md
 - wiki/_MOUSEMOVEMENTY.md
 - wiki/_MOUSEPIPEOPEN.md
 - wiki/_MOUSESHOW.md
 - wiki/_MOUSEWHEEL.md
 - wiki/_MOUSEX.md
 - wiki/_MOUSEY.md
 - wiki/_NEWIMAGE.md
 - wiki/_NUMLOCK-(function).md
 - wiki/_NUMLOCK.md
 - wiki/_OFFSET-(function).md
 - wiki/_OFFSET.md
 - wiki/_OPENCLIENT.md
 - wiki/_OPENCONNECTION.md
 - wiki/_OPENHOST.md
 - wiki/_OS$.md
 - wiki/_PALETTECOLOR-(function).md
 - wiki/_PALETTECOLOR.md
 - wiki/_PI.md
 - wiki/_PIXELSIZE.md
 - wiki/_PRESERVE.md
 - wiki/_PRINTIMAGE.md
 - wiki/_PRINTMODE-(function).md
 - wiki/_PRINTMODE.md
 - wiki/_PRINTSTRING.md
 - wiki/_PRINTWIDTH.md
 - wiki/_PUTIMAGE.md
 - wiki/_R2D.md
 - wiki/_R2G.md
 - wiki/_READBIT.md
 - wiki/_RED.md
 - wiki/_RED32.md
 - wiki/_RESETBIT.md
 - wiki/_RESIZE-(function).md
 - wiki/_RESIZE.md
 - wiki/_RESIZEHEIGHT.md
 - wiki/_RESIZEWIDTH.md
 - wiki/_RGB.md
 - wiki/_RGB32.md
 - wiki/_RGBA.md
 - wiki/_RGBA32.md
 - wiki/_ROUND.md
 - wiki/_SCREENCLICK.md
 - wiki/_SCREENEXISTS.md
 - wiki/_SCREENHIDE.md
 - wiki/_SCREENICON-(function).md
 - wiki/_SCREENICON.md
 - wiki/_SCREENIMAGE.md
 - wiki/_SCREENMOVE.md
 - wiki/_SCREENPRINT.md
 - wiki/_SCREENSHOW.md
 - wiki/_SCREENX.md
 - wiki/_SCREENY.md
 - wiki/_SCROLLLOCK-(function).md
 - wiki/_SCROLLLOCK.md
 - wiki/_SETALPHA.md
 - wiki/_SETBIT.md
 - wiki/_SHELLHIDE.md
 - wiki/_SHL.md
 - wiki/_SHR.md
 - wiki/_Sidebar.md
 - wiki/_SNDBAL.md
 - wiki/_SNDCLOSE.md
 - wiki/_SNDCOPY.md
 - wiki/_SNDGETPOS.md
 - wiki/_SNDLEN.md
 - wiki/_SNDLIMIT.md
 - wiki/_SNDLOOP.md
 - wiki/_SNDOPEN.md
 - wiki/_SNDOPENRAW.md
 - wiki/_SNDPAUSE.md
 - wiki/_SNDPAUSED.md
 - wiki/_SNDPLAY.md
 - wiki/_SNDPLAYCOPY.md
 - wiki/_SNDPLAYFILE.md
 - wiki/_SNDPLAYING.md
 - wiki/_SNDRATE.md
 - wiki/_SNDRAW.md
 - wiki/_SNDRAWDONE.md
 - wiki/_SNDRAWLEN.md
 - wiki/_SNDSETPOS.md
 - wiki/_SNDSTOP.md
 - wiki/_SNDVOL.md
 - wiki/_SOURCE-(function).md
 - wiki/_SOURCE.md
 - wiki/_STARTDIR$.md
 - wiki/_STRCMP.md
 - wiki/_STRICMP.md
 - wiki/_TITLE$.md
 - wiki/_TITLE.md
 - wiki/_TOGGLEBIT.md
 - wiki/_TOTALDROPPEDFILES.md
 - wiki/_TRIM$.md
 - wiki/_UNSIGNED.md
 - wiki/_WHEEL.md
 - wiki/_WIDTH-(function).md
 - wiki/_WINDOWHANDLE.md
 - wiki/_WINDOWHASFOCUS.md